# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170718_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
