# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
