# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0003_userlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pict',
            name='favourite',
        ),
    ]
