# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0004_remove_pict_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='image',
            new_name='image_id',
        ),
        migrations.RemoveField(
            model_name='pict',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.AddField(
            model_name='pict',
            name='image_id',
            field=models.AutoField(default=3456, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pict',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
