# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfiecontest', '0006_userlike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pict',
            name='user',
        ),
        migrations.AddField(
            model_name='pict',
            name='username',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
