# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0007_auto_20170724_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pict',
            old_name='username',
            new_name='user',
        ),
    ]
