# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0008_auto_20170724_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='image_id',
            field=models.IntegerField(),
        ),
    ]
