# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0011_auto_20170724_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
