# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0012_auto_20170724_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='like_id',
        ),
        migrations.AlterField(
            model_name='userlike',
            name='image_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
