# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfiecontest', '0015_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picto',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=b'')),
                ('like', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pict',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pict',
        ),
    ]
