# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to=b'')),
                ('likes', models.IntegerField(max_length=250)),
            ],
        ),
    ]
