# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_likes_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='john', max_length=250),
            preserve_default=False,
        ),
    ]
