# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contest.Picture'),
            preserve_default=False,
        ),
    ]
