# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.IntegerField(),
        ),
    ]
