# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20170721_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='favourite',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
