# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20170721_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
