# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20170724_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image_id',
        ),
    ]
