# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_remove_picture_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='userlike',
        ),
    ]
